### ISSUE TITLE
Proposal to rename and simplify config 

### ISSUE THREAD

**Issue by targos** [zakodium/eslint-config#23]
- Rename package from `@zakodium/eslint-config` to `eslint-config-zakodium`. This will allow to reference it more simply in our ESLint files: `zakodium/react` instead of `@zakodium/eslint-config/react`.
- Simplify config by removing "bundles". Only export "base" configs (for example, `zakodium/adonis` would just be the Adonis-specific config and would have to be explicitly combined with `zakodium/typescript`).

@zakodium/admin

WDYT?

**Comment by stropitek** [comment]
SGTM. Easier names and compose yourself 👍🏻

**Comment by targos** [comment]
Done.
